# -*- coding: utf-8 -*-
"""Travel Advisories

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wavEuctOgOyJGXkanD4EAR1vTNaT1vmg
"""

!pip install torch torchvision torchaudio
!pip install torch-geometric

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Load country attributes
attributes_df = pd.read_csv("/content/drive/MyDrive/Nneoma/advisories.csv", index_col="Country")

# 🔧 CLEAN THE DATA HERE
attributes_df = attributes_df.applymap(
    lambda x: x.strip() if isinstance(x, str) else x
)

attributes_df = attributes_df.replace({
    'Y': 1, 'N': 0,
    'Yes': 1, 'No': 0,
    'TRUE': 1, 'FALSE': 0
})

attributes_df = attributes_df.apply(pd.to_numeric, errors='coerce').fillna(0)

# (Optional but recommended)
attributes_df = attributes_df.astype(float)
# Now safe to inspect
print(attributes_df.head())

# Load border data
borders_df = pd.read_csv("/content/drive/MyDrive/Nneoma/advisories_borders.csv")
print(borders_df.head())

country_to_idx = {country: i for i, country in enumerate(attributes_df.index)}
idx_to_country = {i: country for country, i in country_to_idx.items()}

import torch

edges = []
for _, row in borders_df.iterrows():
  src = country_to_idx.get(row['Country1'])
  dst = country_to_idx.get(row['Country2'])
  if src is not None and dst is not None:
    edges.append([src, dst])
    edges.append([dst, src]) # undirected graph

edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()
print(edge_index.shape) # should be [2, num_edges]

x = torch.tensor(attributes_df.values, dtype=torch.float)
print(x.shape)

from torch_geometric.data import Data

data = Data(x=x, edge_index=edge_index)
print(data)

import torch.nn as nn
from torch_geometric.nn import SAGEConv

class GraphSAGE(nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super().__init__()
        self.conv1 = SAGEConv(in_channels, hidden_channels)
        self.conv2 = SAGEConv(hidden_channels, out_channels)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        x = torch.relu(x)
        x = self.conv2(x, edge_index)
        return x

model = GraphSAGE(
 in_channels=data.num_node_features,
 hidden_channels=28,
 out_channels=13 # final embedding dimension
)

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = nn.MSELoss()

model.train()
for epoch in range(100):
 optimizer.zero_grad()
 out = model(data) # node embeddings
 loss = criterion(out, data.x) # reconstruct features
 loss.backward()
 optimizer.step()

if epoch % 10 == 0:
  print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

model.eval()
with torch.no_grad():
  embeddings = model(data) # shape: [num_teams, 13]

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
import numpy as np
import torch

def evaluate_clustering(X, k=4, name="Model"):
    X = StandardScaler().fit_transform(X)
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X)

    sil = silhouette_score(X, labels)
    ch = calinski_harabasz_score(X, labels)
    db = davies_bouldin_score(X, labels)

    print(f"\n{name}")
    print(f"Silhouette: {sil:.4f}")
    print(f"Calinski-Harabasz: {ch:.4f}")
    print(f"Davies-Bouldin: {db:.4f}")

    return sil, ch, db


# =========================
# Model A: Full GraphSAGE
# =========================
X_A = embeddings.detach().cpu().numpy()
evaluate_clustering(X_A, k=4, name="Model A (GraphSAGE: Attributes + Graph)")


# =========================
# Model B: Attributes Only
# =========================
X_B = attributes_df.values
evaluate_clustering(X_B, k=4, name="Model B (Attributes Only)")


# =========================
# Model C: Graph Only
# =========================
# Replace features with constant vector
x_const = torch.ones_like(data.x)

data_const = data.clone()
data_const.x = x_const

# Train GraphSAGE again
model_const = GraphSAGE(
    in_channels=data_const.num_node_features,
    hidden_channels=28,
    out_channels=13
)

optimizer = torch.optim.Adam(model_const.parameters(), lr=0.01)
criterion = torch.nn.MSELoss()

model_const.train()
for epoch in range(100):
    optimizer.zero_grad()
    out = model_const(data_const)
    loss = criterion(out, data_const.x)
    loss.backward()
    optimizer.step()

model_const.eval()
with torch.no_grad():
    embeddings_const = model_const(data_const)

X_C = embeddings_const.detach().cpu().numpy()
evaluate_clustering(X_C, k=4, name="Model C (Graph Only)")

results = {
    "GraphSAGE": evaluate_clustering(X_A),
    "Attributes": evaluate_clustering(X_B),
    "GraphOnly": evaluate_clustering(X_C)
}

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
import numpy as np
import torch

def evaluate_clustering(X, k=4, name="Model"):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X)

    sil = silhouette_score(X, labels)
    ch = calinski_harabasz_score(X, labels)
    db = davies_bouldin_score(X, labels)

    print(f"\n{name}")
    print(f"Silhouette: {sil:.4f}")
    print(f"Calinski-Harabasz: {ch:.4f}")
    print(f"Davies-Bouldin: {db:.4f}")

    return sil, ch, db

#Model A: Full GraphSAGE
X_A = embeddings.detach().cpu().numpy()
evaluate_clustering(X_A, k=4, name="Model A (GraphSAGE: Attributes + Graph)")

#Model B: Attributes Only
X_B = attributes_df.values
evaluate_clustering(X_B, k=4, name="Model B (Attributes Only)")

# Model C: Graph Only
x_const = torch.ones_like(data.x)

data_const = data.clone()
data_const.x = x_const

model_const = GraphSAGE(
    in_channels=data_const.num_node_features,
    hidden_channels=28,
    out_channels=13
)

optimizer = torch.optim.Adam(model_const.parameters(), lr=0.01)
criterion = torch.nn.MSELoss()

model_const.train()
for epoch in range(100):
    optimizer.zero_grad()
    out = model_const(data_const)
    loss = criterion(out, data_const.x)
    loss.backward()
    optimizer.step()

model_const.eval()
with torch.no_grad():
    embeddings_const = model_const(data_const)

X_C = embeddings_const.detach().cpu().numpy()
evaluate_clustering(X_C, k=4, name="Model C (Graph Only)")


results = {
    "GraphSAGE": evaluate_clustering(X_A),
    "Attributes": evaluate_clustering(X_B),
    "GraphOnly": evaluate_clustering(X_C)
}

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

sse = []
k_range = range(2, 11) # Try cluster counts from 2 to 10

for k in k_range:
  kmeans = KMeans(n_clusters=k, random_state=42)
  kmeans.fit(embeddings)
  sse.append(kmeans.inertia_) # Sum of squared distances to centroids

# Plot the elbow curve
plt.figure(figsize=(8, 5))
plt.plot(k_range, sse, marker='o')
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Sum of Squared Errors (SSE)")
plt.title("Elbow Method for Choosing k")
plt.grid(True)
plt.show()

from sklearn.metrics import silhouette_score

print("Silhouette scores:")
for k in k_range:
  kmeans = KMeans(n_clusters=k, random_state=42)
  labels = kmeans.fit_predict(embeddings)
  score = silhouette_score(embeddings, labels)
  print(f"k = {k}, silhouette score = {score:.4f}")

scores = []
for k in k_range:
  kmeans = KMeans(n_clusters=k, random_state=42)
  labels = kmeans.fit_predict(embeddings)
  scores.append(silhouette_score(embeddings, labels))

plt.figure(figsize=(8, 5))
plt.plot(k_range, scores, marker='o', color='green')
plt.xlabel("Number of clusters (k)")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Scores for Different k")
plt.grid(True)
plt.show()

from sklearn.cluster import KMeans

kmeans_4 = KMeans(n_clusters=4, random_state=42)
labels_k4 = kmeans_4.fit_predict(embeddings)

cluster_df = pd.DataFrame({
'Country': list(attributes_df.index),
'cluster_k4': labels_k4,
})



cluster_df = cluster_df.merge(attributes_df, left_on='Country', right_index=True)
print(cluster_df.head())

summary_k4 = cluster_df.groupby('cluster_k4').mean(numeric_only=True)
print("Cluster characteristics (k=4):")
print(summary_k4)

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
pca = PCA(n_components=2)
reduced = pca.fit_transform(embeddings)
plt.figure(figsize=(8, 6))
scatter = plt.scatter(reduced[:, 0], reduced[:, 1], c=labels_k4, cmap='tab10', s=50)
plt.legend(*scatter.legend_elements(), title="Cluster k=4")
plt.title("Country Clusters via GraphSAGE + PCA")
plt.xlabel("PCA1")
plt.ylabel("PCA2")
plt.grid(True)
plt.show()

import pandas as pd

boolean_cols = ['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Crime (C)', 'Terrorism (T)', 'Unrest (U)', 'Health (H)', 'Natural Disaster (N)', 'Time-Limited Event (E)', 'Kidnapping (K)', 'Detention (D)', 'Other (O)']

category_cols = []

def summarize_clusters(df, cluster_col):
    summaries = []
    for cluster, group in df.groupby(cluster_col):
        summary = {
            'cluster': cluster,
            'count': len(group)
        }
        # Boolean features → proportion True
        for col in boolean_cols:
            summary[col] = group[col].mean() * 100  # % True

        summaries.append(summary)

    return pd.DataFrame(summaries).sort_values('cluster')

summary_k4 = summarize_clusters(cluster_df, 'cluster_k4')
print("=== K=4 Cluster Summary ===")
print(summary_k4)

from sklearn.cluster import KMeans
import pandas as pd

kmeans_4 = KMeans(n_clusters=4, random_state=42)
cluster_df['cluster_k4'] = kmeans_4.fit_predict(embeddings)

clusters_k4_df = cluster_df.groupby('cluster_k4')['Country'].apply(list).reset_index()
print("\nCountries per cluster (k=4):")
print(clusters_k4_df)

clusters_k4_df.to_csv("countries_per_cluster_k4.csv", index=False)

from google.colab import files
files.download('countries_per_cluster_k4.csv')

import seaborn as sns
import matplotlib.pyplot as plt

cluster_col = 'cluster_k4'

feature_cols = ['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Crime (C)', 'Terrorism (T)', 'Unrest (U)', 'Health (H)', 'Natural Disaster (N)', 'Time-Limited Event (E)', 'Kidnapping (K)', 'Detention (D)', 'Other (O)']

cluster_summary = cluster_df.groupby(cluster_col)[feature_cols].mean()

plt.figure(figsize=(10, 6))
sns.heatmap(cluster_summary, annot=True, cmap='YlGnBu', cbar_kws={'label': 'Proportion'})
plt.title(f'Cluster Characteristics Heatmap ({cluster_col})')
plt.ylabel('Cluster')
plt.xlabel('Feature')
plt.tight_layout()
plt.show()

from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score

for k, labels in [('k4', cluster_df['cluster_k4'])]:
    X_emb = embeddings  # GraphSAGE embeddings
    print(k,
          'Silhouette:', silhouette_score(X_emb, labels),
          'Calinski-Harabasz:', calinski_harabasz_score(X_emb, labels),
          'Davies-Bouldin:', davies_bouldin_score(X_emb, labels))

import umap
import matplotlib.pyplot as plt

feature_cols = ['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Crime (C)', 'Terrorism (T)', 'Unrest (U)', 'Health (H)', 'Natural Disaster (N)', 'Time-Limited Event (E)', 'Kidnapping (K)', 'Detention (D)', 'Other (O)']
X = attributes_df[feature_cols].values

def plot_umap(X, labels, title):
    reducer = umap.UMAP(random_state=42)
    embedding = reducer.fit_transform(X)

    plt.figure(figsize=(8,6))
    scatter = plt.scatter(embedding[:,0], embedding[:,1], c=labels, cmap="tab10", s=50, alpha=0.8)
    plt.title(title)
    plt.xlabel("UMAP-1")
    plt.ylabel("UMAP-2")
    plt.colorbar(scatter, label="Cluster")
    plt.show()

plot_umap(X, cluster_df["cluster_k4"], "UMAP Projection (k=4)")

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score

k_values = range(2, 11)

ch_scores = []
db_scores = []

for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X)

    # Calculate Calinski-Harabasz and Davies-Bouldin scores
    ch_scores.append(calinski_harabasz_score(X, labels))
    db_scores.append(davies_bouldin_score(X, labels))

# --- Plot Calinski-Harabasz ---
plt.figure(figsize=(8, 5))
plt.plot(k_values, ch_scores, 'o-', color='blue')
plt.title("Calinski-Harabasz Scores for Different k")
plt.xlabel("Number of clusters (k)")
plt.ylabel("Calinski-Harabasz Score")
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(k_values, db_scores, 'o-', color='red')
plt.title("Davies-Bouldin Scores for Different k")
plt.xlabel("Number of clusters (k)")
plt.ylabel("Davies-Bouldin Score")
plt.show()

cluster_id = 0
cluster_countries = cluster_df[cluster_df['cluster_k4'] == cluster_id]['Country'].unique()
print(f"Countries in Cluster {cluster_id}: {cluster_countries}")

cluster_matches = borders_df[borders_df['Country1'].isin(cluster_countries)]

opponent_counts = cluster_matches['Country2'].value_counts().head(10)
print("\nTop common opponents:")
print(opponent_counts)

cluster_attributes = cluster_df[cluster_df['Country'].isin(cluster_countries)]

attribute_means = cluster_attributes.mean(numeric_only=True)
print("\nCluster attribute averages (% True or avg):")
print(attribute_means)

cluster_summary = cluster_attributes.copy()
print("\n=== Combined Cluster Summary ===")
print(cluster_summary)

cluster_summary.to_csv(f"cluster_summary.csv", index=False)

from google.colab import files
files.download('cluster_summary.csv')

import numpy as np
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Nneoma/advisories.csv")

df.columns = df.columns.str.strip()

df = df.merge(cluster_df[['Country', 'cluster_k4']], on='Country', how='left')

risk_columns = ['Level 1', 'Level 2', 'Level 3', 'Level 4',
                'Crime (C)', 'Terrorism (T)', 'Unrest (U)', 'Health (H)',
                'Natural Disaster (N)', 'Time-Limited Event (E)',
                'Kidnapping (K)', 'Detention (D)', 'Other (O)']

weights = np.ones(len(risk_columns)) / len(risk_columns)  # equal weights

df['risk_score'] = df[risk_columns].mul(weights).sum(axis=1)

cluster_risk = df.groupby('cluster_k4')['risk_score'].mean().sort_values()
print("\n=== Average Risk per Cluster ===")
print(cluster_risk)

node_embeddings = embeddings.detach().cpu().numpy()

reducer = umap.UMAP(n_components=2, random_state=42)
umap_coords = reducer.fit_transform(node_embeddings)

cluster_df = cluster_df.reset_index(drop=True).copy()
cluster_df["umap1"] = umap_coords[:, 0]
cluster_df["umap2"] = umap_coords[:, 1]

cluster_risk_order = cluster_risk.sort_values().index.tolist()

start_cluster = cluster_risk_order[0]
end_cluster = cluster_risk_order[-1]

start_point = cluster_df[cluster_df.cluster_k4 == start_cluster][["umap1", "umap2"]].mean().values
end_point   = cluster_df[cluster_df.cluster_k4 == end_cluster][["umap1", "umap2"]].mean().values

arrow_dx = end_point[0] - start_point[0]
arrow_dy = end_point[1] - start_point[1]

plt.figure(figsize=(10, 7))
plt.scatter(cluster_df["umap1"], cluster_df["umap2"],
            c=cluster_df["cluster_k4"], cmap="tab10", s=60, alpha=0.8)

plt.arrow(start_point[0], start_point[1],
          arrow_dx, arrow_dy,
          width=0.02, length_includes_head=True,
          head_width=0.25, color="black")

plt.text(start_point[0], start_point[1], "Low risk", fontsize=12)
plt.text(end_point[0], end_point[1], "High risk", fontsize=12)

plt.title("UMAP Projection with Estimated Risk Gradient")
plt.xlabel("UMAP 1")
plt.ylabel("UMAP 2")
plt.grid(True)
plt.show()

import plotly.express as px

risk_df = pd.read_excel('/content/drive/MyDrive/Risk Gradient.xlsx')
risk_df.columns = ['country', 'cluster', 'risk']

fig = px.choropleth(
    risk_df,
    locations="country",
    locationmode="country names",
    color="risk",
    color_continuous_scale="Viridis",
    title="Global Risk Choropleth Map",
)

fig.update_layout(
    margin=dict(l=0, r=0, t=40, b=0)
)

fig.show()

!pip install cartopy

import pandas as pd
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

df = pd.read_excel('/content/drive/MyDrive/Risk Gradient.xlsx')
df.columns = ["country", "cluster", "risk"]

risk_lookup = dict(zip(df["country"], df["risk"]))

import cartopy.io.shapereader as shpreader
shp = shpreader.natural_earth(resolution="110m",
                              category="cultural",
                              name="admin_0_countries")

fig = plt.figure(figsize=(14, 7), dpi=300)
ax = plt.axes(projection=ccrs.Robinson())
ax.set_global()
ax.coastlines()

cmap = plt.cm.viridis
norm = plt.Normalize(df["risk"].min(), df["risk"].max())

for country in shpreader.Reader(shp).records():
    name = country.attributes["NAME_LONG"]

    if name in risk_lookup:
        risk_value = risk_lookup[name]
        facecolor = cmap(norm(risk_value))
    else:
        facecolor = (0.9, 0.9, 0.9)   # light gray for missing values

    ax.add_geometries(
        country.geometry,
        crs=ccrs.PlateCarree(),
        facecolor=facecolor,
        edgecolor="black",
        linewidth=0.2
    )

sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
sm.set_array([])
cbar = plt.colorbar(sm, ax=ax, shrink=0.6, pad=0.03)
cbar.set_label("Risk Score", fontsize=12)

plt.title("Global Risk Choropleth Map", fontsize=16)
plt.tight_layout()

plt.savefig("risk_choropleth.png", dpi=300)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.io.shapereader as shpreader

df = pd.read_excel("/content/drive/MyDrive/Risk Gradient.xlsx")
df.columns = ["country", "cluster", "risk"]

cluster_lookup = dict(zip(df["country"], df["cluster"]))

shp = shpreader.natural_earth(resolution="110m",
                              category="cultural",
                              name="admin_0_countries")

fig = plt.figure(figsize=(14, 7), dpi=300)
ax = plt.axes(projection=ccrs.Robinson())
ax.set_global()
ax.coastlines()

# categorical cmap
cmap = plt.cm.tab10

for country in shpreader.Reader(shp).records():
    name = country.attributes["NAME_LONG"]

    if name in cluster_lookup:
        cluster_value = cluster_lookup[name]
        facecolor = cmap(cluster_value % 10)
    else:
        facecolor = (0.9, 0.9, 0.9)

    ax.add_geometries(
        country.geometry,
        crs=ccrs.PlateCarree(),
        facecolor=facecolor,
        edgecolor="black",
        linewidth=0.2
    )

plt.title("Global Country Clusters (k = 4)", fontsize=16)
plt.tight_layout()
plt.savefig("cluster_map.png", dpi=300)
plt.show()

#IV. Side by side (risk and cluster in one figure)

import numpy as np

fig, axes = plt.subplots(1, 2, figsize=(18, 7), dpi=300,
                         subplot_kw={'projection': ccrs.Robinson()})

risk_lookup = dict(zip(df["country"], df["risk"]))

shp_reader = shpreader.Reader(shp)

# ---- Left: Risk map ----
ax = axes[0]
ax.set_global(); ax.coastlines()
cmap_risk = plt.cm.viridis
norm_risk = plt.Normalize(df["risk"].min(), df["risk"].max())

for country in shp_reader.records():
    name = country.attributes["NAME_LONG"]
    if name in risk_lookup:
        fc = cmap_risk(norm_risk(risk_lookup[name]))
    else:
        fc = (0.9, 0.9, 0.9)

    ax.add_geometries(country.geometry, ccrs.PlateCarree(),
                      facecolor=fc, edgecolor="black", linewidth=0.2)

ax.set_title("Risk Score by Country")

# colorbar
sm = plt.cm.ScalarMappable(cmap=cmap_risk, norm=norm_risk)
sm.set_array([])
fig.colorbar(sm, ax=ax, shrink=0.6, pad=0.03, label="Risk Score")

# ---- Right: Cluster map ----
ax = axes[1]
ax.set_global(); ax.coastlines()
cmap_cluster = plt.cm.tab10

for country in shpreader.Reader(shp).records():
    name = country.attributes["NAME_LONG"]
    if name in cluster_lookup:
        fc = cmap_cluster(cluster_lookup[name] % 10)
    else:
        fc = (0.9, 0.9, 0.9)

    ax.add_geometries(country.geometry, ccrs.PlateCarree(),
                      facecolor=fc, edgecolor="black", linewidth=0.2)

ax.set_title("Cluster Assignment (k = 4)")

plt.tight_layout()
plt.savefig("risk_cluster_side_by_side.png", dpi=300)
plt.show()

fig = plt.figure(figsize=(14, 7), dpi=300)
ax = plt.axes(projection=ccrs.Robinson())
ax.set_global()
ax.coastlines(color="black")

cmap = plt.cm.Greys
norm = plt.Normalize(df["risk"].min(), df["risk"].max())

for country in shpreader.Reader(shp).records():
    name = country.attributes["NAME_LONG"]
    if name in risk_lookup:
        fc = cmap(norm(risk_lookup[name]))
    else:
        fc = (0.95, 0.95, 0.95)

    ax.add_geometries(country.geometry, ccrs.PlateCarree(),
                      facecolor=fc, edgecolor="black", linewidth=0.25)

sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
sm.set_array([])
plt.colorbar(sm, ax=ax, shrink=0.6, label="Risk Score")

plt.title("Risk Choropleth (High-Contrast Grayscale)", fontsize=16)
plt.tight_layout()
plt.savefig("risk_map_grayscale.png", dpi=300)
plt.show()

import umap
import numpy as np

X_umap = umap.UMAP(random_state=42).fit_transform(df[["risk"]])

fig = plt.figure(figsize=(15, 7), dpi=300)

ax1 = fig.add_subplot(1, 2, 1)
sc = ax1.scatter(X_umap[:,0], X_umap[:,1],
                 c=df["risk"], cmap="viridis", s=25)
ax1.set_title("UMAP Projection Colored by Risk")
ax1.set_xlabel("UMAP-1"); ax1.set_ylabel("UMAP-2")
plt.colorbar(sc, ax=ax1, label="Risk Score")

ax2 = fig.add_subplot(1, 2, 2, projection=ccrs.Robinson())
ax2.set_global(); ax2.coastlines()

for country in shpreader.Reader(shp).records():
    name = country.attributes["NAME_LONG"]
    if name in risk_lookup:
        fc = plt.cm.viridis(norm_risk(risk_lookup[name]))
    else:
        fc = (0.9, 0.9, 0.9)

    ax2.add_geometries(country.geometry, ccrs.PlateCarree(),
                       facecolor=fc, edgecolor="black", linewidth=0.2)

ax2.set_title("Geographic Distribution of Risk")

plt.tight_layout()
plt.savefig("umap_plus_choropleth.png", dpi=300)
plt.show()